# Generated by Django 3.2.8 on 2021-10-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic_sched',
            new_name='Topic_plan',
        ),
    ]
