# Generated by Django 3.2.8 on 2021-10-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0002_rename_topic_sched_topic_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_branchs.topic_plan')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
