# Generated by Django 3.2.8 on 2021-10-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0003_entry_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry_plan',
            options={'verbose_name_plural': 'entries_plan'},
        ),
    ]
