# Generated by Django 3.2.8 on 2021-10-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0004_alter_entry_plan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_plan',
            name='cover',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('topic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='green_branchs.topic_plan')),
            ],
        ),
    ]
