# Generated by Django 3.2.8 on 2021-10-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0005_auto_20211014_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
