# Generated by Django 3.2.8 on 2021-10-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0006_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_plan',
            name='cover',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
