# Generated by Django 3.2.8 on 2021-10-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_branchs', '0008_entry_activ_entry_prod_entry_rec_entry_sched_topic_activ_topic_prod_topic_rec_topic_sched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_sched',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='topic_sched',
            name='cover',
        ),
    ]
